language: r
sudo: false
cache: packages
apt_packages:
  - libudunits2-dev
  - libgdal-dev
  - libgeos-dev
  - libproj-dev
git:
  depth: false
script:
- Rscript -e 'rmarkdown::render("wq.Rmd")'
- git config --global user.name "fawda123"
- git config --global user.email "mbafs2012@gmail.com"
- git pull https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
- git add -A
- git commit -a -m "Updating wq rmd build via travis-ci.org [ci skip]"
- git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
notifications:
  email:
    recipients:
    - mbafs2012@gmail.com
    - ben@ecoquants.com
    on_success: change
    on_failure: change
env:
  global:
  - TRAVIS_REPO_SLUG=tbep-tech/wq-static
  - TRAVIS_BRANCH=master
  - CRAN: http://cran.rstudio.com
  - secure: Ix1SzTbkNbqaBWjWeTMz/in5J7+lf82gPq6vWGflpyJVensikKDuM4S8Jm9XnHzYUaZYJz9e/CCBXkSx5kPDRC8YtJcNWBIwFS8qUbBAXfXvGunhWViaZh4aGaXRZ9ax6Rl26l4lBQN6W7/CbGfpSYSCuGsPOlIwCx+7bfV7m7JYltIVPEae1enUlTjxTjupSvpcA6gY/iRAhfJ/VSJVp2okZA6lORN/fOa/eafsL3F60sCFqu81Vr5oOAU3AsLh+vJlJRzqzpiv1nFXH6VTb1v6WhDUm67vL8dQYLMhUFBov4lim/FN9HgeHbWvSs2dNzcznCfUz4sMUDWa/mm5t39swVwbz9YNv7L4oaxahIyT/pSlbZz8rbjnDG+cj4YOLikTzp3SGwkng1J9tCaZvaIN2wS4MKuBYSJVA2S6vhQ+uJF87o44TE9xZjxcBMULXlcb+ZHXCSgTtHJwJ72/0b7395S7IXAdIl5sHHLqmFIGYGKOOXqa4xh+VaLdZ0A1UcSWoHbbfwmqDrL+UlKOntv+/kodkW+LK7khY3+FN6QBaOFUec8xvZEWxjl2CrknDYWAKno49Gg2ovJpWTOICzVJKNoYJ/PyFSqqtfc0wTFJ+F4ZJs9pXV/Vp3v/paaUU5N8VBG8vNkKbXK4qA53lJs3dZXaaHh3nEzr7TOAQ1o=
